import Box from '@mui/material/Box';
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import Typography from '@mui/material/Typography';
import SyncIcon from '@mui/icons-material/Sync';
import type { KubeObject } from '@kubus/shared';
import { useResourceList } from '../../../api/queries.js';
import { AgeCell } from '../../AgeCell.js';
import { ConditionsTable } from '../GenericDetail.js';
import { CustomResourceFooter } from '../CustomResourceDetail.js';
import { Fact, FactLink, Facts, WarnValue } from '../Facts.js';
import { conditionOf } from './gateway-api.js';
import { ProblemBanner } from '../ProblemBanner.js';
import { DetailStack, Section } from '../Section.js';
import { SummaryStrip } from '../SummaryStrip.js';
import { useObjectOpener } from './links.js';
import { conditionTile } from './tiles.js';
import { OperatorActionButtons } from './OperatorActionButtons.js';
import type { CustomKindActionProps, CustomKindViewProps } from './registry.js';

interface RemoteRef {
  key?: string;
  property?: string;
  version?: string;
}

interface ExternalSecretSpec {
  refreshInterval?: string;
  secretStoreRef?: { name?: string; kind?: string };
  target?: { name?: string; creationPolicy?: string; deletionPolicy?: string; template?: unknown };
  data?: Array<{ secretKey?: string; remoteRef?: RemoteRef; sourceRef?: { storeRef?: { name?: string; kind?: string } } }>;
  dataFrom?: Array<{ extract?: RemoteRef; find?: { name?: { regexp?: string }; tags?: Record<string, string>; path?: string }; sourceRef?: { generatorRef?: { kind?: string; name?: string } } }>;
}

interface ExternalSecretStatus {
  refreshTime?: string;
  syncedResourceVersion?: string;
  binding?: { name?: string };
}

/** One line for a dataFrom entry: which remote keys it pulls in wholesale. */
function dataFromText(entry: NonNullable<ExternalSecretSpec['dataFrom']>[number]): string {
  if (entry.extract) return `all properties of ${entry.extract.key ?? '?'}${entry.extract.version ? ` @${entry.extract.version}` : ''}`;
  if (entry.find) {
    const parts = [entry.find.name?.regexp && `name ~ ${entry.find.name.regexp}`, entry.find.path && `under ${entry.find.path}`, ...Object.entries(entry.find.tags ?? {}).map(([k, v]) => `tag ${k}=${v}`)];
    return `every secret with ${parts.filter(Boolean).join(', ') || 'any name'}`;
  }
  if (entry.sourceRef?.generatorRef) return `generated by ${entry.sourceRef.generatorRef.kind ?? 'generator'} ${entry.sourceRef.generatorRef.name ?? ''}`.trim();
  return 'unknown source';
}

/** ExternalSecret status word for the drawer header. */
export function readyHeaderStatus(obj: KubeObject): string | undefined {
  const ready = conditionOf(obj, 'Ready');
  return ready ? (ready.status === 'True' ? 'Ready' : ready.status === 'False' ? 'NotReady' : 'Unknown') : undefined;
}

/**
 * ExternalSecret: whether the last sync worked, when it ran, which store it
 * reads and which Secret it writes, and the key mapping between the two.
 */
export function ExternalSecretDetail({ obj, ctx, crd, version }: CustomKindViewProps) {
  const open = useObjectOpener(ctx);
  const namespace = obj.metadata.namespace;
  const spec = (obj.spec ?? {}) as ExternalSecretSpec;
  const status = (obj.status ?? {}) as ExternalSecretStatus;
  const ready = conditionOf(obj, 'Ready');
  const targetName = spec.target?.name || obj.metadata.name;
  const creation = spec.target?.creationPolicy ?? 'Owner';
  // The target Secret's existence decides between a link and "not created
  // yet"; a name-selected list answers that without a 404 to retry.
  const secretQuery = useResourceList(namespace && creation !== 'None' ? { ctx, group: '', version: 'v1', plural: 'secrets', namespace, fieldSelector: `metadata.name=${targetName}` } : undefined);
  const secretMissing = !!secretQuery.data && secretQuery.data.items.length === 0;
  const secretOpener = open({ group: '', kind: 'Secret', name: targetName, namespace });
  const storeKind = spec.secretStoreRef?.kind ?? 'SecretStore';
  const storeName = spec.secretStoreRef?.name;
  const storeGroup = (obj.apiVersion ?? 'external-secrets.io/v1').split('/')[0] ?? 'external-secrets.io';
  const storeOpener = storeName ? open({ group: storeGroup, kind: storeKind, name: storeName, namespace: storeKind === 'SecretStore' ? namespace : undefined }) : undefined;
  const data = spec.data ?? [];
  const dataFrom = spec.dataFrom ?? [];

  return (
    <DetailStack>
      <SummaryStrip
        items={[
          conditionTile('Ready', ready),
          { label: 'Last sync', value: status.refreshTime ? <><AgeCell timestamp={status.refreshTime} variant="inherit" /> ago</> : 'never' },
          { label: 'Refresh', value: spec.refreshInterval === '0' || spec.refreshInterval === '0s' ? 'once' : (spec.refreshInterval ?? '1h'), hint: 'How often the store is read again.' },
          { label: 'Keys', value: String(data.length + dataFrom.length), hint: 'Mapped keys plus bulk (dataFrom) entries.' },
        ]}
      />
      {ready?.status === 'False' && (
        <ProblemBanner severity="error" title="Why this secret isn’t syncing" items={[{ title: ready.reason ?? 'NotReady', message: ready.message, at: ready.lastTransitionTime }]} />
      )}
      <Section title="Sync">
        <Facts>
          <Fact label="Store">
            {storeName && (storeOpener ? <FactLink onClick={storeOpener}>{`${storeKind} ${storeName}`}</FactLink> : `${storeKind} ${storeName}`)}
          </Fact>
          <Fact label="Target secret">
            {secretMissing ? (
              <>
                {targetName} <WarnValue>not created yet</WarnValue>
              </>
            ) : secretOpener ? (
              <FactLink onClick={secretOpener}>{targetName}</FactLink>
            ) : (
              targetName
            )}
          </Fact>
          <Fact label="Creation policy" hint="Owner: the ExternalSecret owns the Secret. Merge: keys are merged into an existing Secret. None: nothing is written.">
            {creation}
          </Fact>
          <Fact label="Deletion policy" hint="What happens to the Secret's keys when the provider no longer has them.">
            {spec.target?.deletionPolicy ?? 'Retain'}
          </Fact>
          <Fact label="Template">{spec.target?.template ? 'Yes, the Secret is rendered from a template' : undefined}</Fact>
          <Fact label="Synced version" mono hint="Resource version of the ExternalSecret the last sync ran for.">
            {status.syncedResourceVersion}
          </Fact>
        </Facts>
      </Section>
      <Section title="Data" count={data.length + dataFrom.length} flush>
        {data.length + dataFrom.length === 0 ? (
          <Typography variant="body2" color="text.secondary" sx={{ px: 1.5, py: 1 }}>
            No keys mapped.
          </Typography>
        ) : (
          <Table size="small">
            <TableHead>
              <TableRow>
                <TableCell>Secret key</TableCell>
                <TableCell>From</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {data.map((d, i) => (
                <TableRow key={`d${i}`} sx={{ verticalAlign: 'top' }}>
                  <TableCell sx={{ fontFamily: 'monospace', fontSize: 12.5, wordBreak: 'break-all' }}>{d.secretKey ?? '?'}</TableCell>
                  <TableCell sx={{ fontFamily: 'monospace', fontSize: 12.5, wordBreak: 'break-all' }}>
                    {d.remoteRef?.key ?? '?'}
                    {d.remoteRef?.property && (
                      <Box component="span" sx={{ color: 'text.secondary', fontFamily: 'inherit' }}>
                        {' '}
                        → {d.remoteRef.property}
                      </Box>
                    )}
                    {d.remoteRef?.version && (
                      <Box component="span" sx={{ color: 'text.secondary', fontFamily: 'inherit' }}>
                        {' '}
                        @{d.remoteRef.version}
                      </Box>
                    )}
                  </TableCell>
                </TableRow>
              ))}
              {dataFrom.map((d, i) => (
                <TableRow key={`f${i}`} sx={{ verticalAlign: 'top' }}>
                  <TableCell sx={{ color: 'text.secondary' }}>all keys</TableCell>
                  <TableCell sx={{ wordBreak: 'break-word' }}>{dataFromText(d)}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        )}
      </Section>
      <ConditionsTable obj={obj} />
      <CustomResourceFooter obj={obj} ctx={ctx} crd={crd} version={version} />
    </DetailStack>
  );
}

/** Force refresh: sync from the store now instead of at the next interval. */
export function ExternalSecretActions(props: CustomKindActionProps) {
  return (
    <OperatorActionButtons
      target={props}
      actions={[{ action: 'eso-force-sync', label: 'Force refresh', icon: <SyncIcon />, emphasis: true, done: `Refresh requested for ${props.obj.metadata.name}` }]}
    />
  );
}
